Mantle color
mantle-labs/console pull request #1
Opened 2022-09-26 17:13 UTC by ben-nole

Ca fait vraiment un pr pas nice, vous pouvez skiper genre la moitier des premieres files a review

2022-09-27 19:07 UTC, MantleFounder approved these changes

2022-09-27 22:39 UTC, nic758 requested changes
![image](https://user-images.githubusercontent.com/9924300/192649835-7ef2d367-e975-4654-8dd5-61754ea52bad.png)
On voit pas trop bien le mantle l'ecriture devrait etre blanc
![image](https://user-images.githubusercontent.com/9924300/192649931-054fa10a-2117-41de-ae53-5e78053cda4a.png)
il y a encore plus de place ou ca parle de minIO, les onglets Support, license, documentations et surment d'autre.

2022-09-28 16:36 UTC, ben-nole commented
> ![image](https://user-images.githubusercontent.com/9924300/192649835-7ef2d367-e975-4654-8dd5-61754ea52bad.png) On voit pas trop bien le mantle l'ecriture devrait etre blanc ![image](https://user-images.githubusercontent.com/9924300/192649931-054fa10a-2117-41de-ae53-5e78053cda4a.png) il y a encore plus de place ou ca parle de minIO, les onglets Support, license, documentations et surment d'autre.

![image](https://user-images.githubusercontent.com/83972813/192837778-aa1bf05e-79ac-4d53-be7d-65cddd4d3ab4.png)
 Jpense faut tu pull

2022-09-30 17:46 UTC, nic758 approved these changes

2022-09-30 17:46 UTC, merged