Feature/translate
mantle-labs/console pull request #12
Opened 2022-10-25 13:03 UTC by ben-nole

2022-10-28 14:10 UTC, MantleFounder requested changes

2022-10-28 14:10 UTC, MantleFounder commented on portal-ui/src/screens/Console/NotificationEndpoints/NotificationEndpoints.tsx
Translate this
![image](https://user-images.githubusercontent.com/38961332/198634017-c717567c-712a-4df7-82e5-24cf4238ac42.png)

2022-10-28 14:10 UTC, MantleFounder commented on portal-ui/src/screens/Console/NotificationEndpoints/NotificationEndpoints.tsx
Dans le fond je crois que ON et OFF c'est correct de les laissés dememe

2022-11-11 20:15 UTC, nic758 approved these changes

2022-11-25 22:27 UTC, nic758 approved these changes

2022-11-25 23:14 UTC, MantleFounder approved these changes

2022-11-25 23:15 UTC, merged