removed the view with object info to make it more consistent so that …
mantle-labs/console pull request #33
Opened 2022-11-30 20:11 UTC by ben-nole

…user doesnt get lost in directories

2022-11-30 21:27 UTC, MantleFounder requested changes
There is a bug when you:
1)click on an item 
2)click on the box of that same item
3)click on the box again of that same item
The side menu completely disappear and the box gets unchecked
![image](https://user-images.githubusercontent.com/38961332/204911652-d3f91460-c640-49f8-82a9-e70aa8f6f049.png)

2022-12-01 16:34 UTC, nic758 approved these changes

2022-12-01 17:01 UTC, MantleFounder requested changes
Add folder in bucket does not work with the button "create Path"
![image](https://user-images.githubusercontent.com/38961332/205114173-692df94c-282c-4c3b-9948-9dc13eb0a1e6.png)

2022-12-01 19:21 UTC, MantleFounder approved these changes

2022-12-01 20:15 UTC, nic758 approved these changes

2022-12-01 20:18 UTC, merged